// <auto-generated />
namespace ERManagement.WEBUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HRDBEmployeeCRUD2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HRDBEmployeeCRUD2));
        
        string IMigrationMetadata.Id
        {
            get { return "202212081312297_HR-DB-EmployeeCRUD-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
